# Generated by Django 5.1.1 on 2024-10-05 15:59

import django.utils.timezone
import users.models.users
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('created_by', models.UUIDField(editable=False, help_text='the Id of the digithai note app account user who added this object', null=True, verbose_name='created by')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='last modified date')),
                ('last_modified_by', models.UUIDField(editable=False, help_text='the id of the account user who last modified this object', null=True, verbose_name='last modified by')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False, verbose_name='id')),
                ('email_address', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('first_name', models.CharField(blank=True, default='', editable=False, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default='', editable=False, max_length=150, verbose_name='first name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
                'indexes': [models.Index(fields=['email_address'], name='users_accou_email_a_d7e722_idx')],
            },
            managers=[
                ('objects', users.models.users.UserManager()),
            ],
        ),
    ]
