# Generated by Django 5.1.1 on 2024-10-05 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('created_by', models.UUIDField(editable=False, help_text='the Id of the digithai note app account user who added this object', null=True, verbose_name='created by')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='last modified date')),
                ('last_modified_by', models.UUIDField(editable=False, help_text='the id of the account user who last modified this object', null=True, verbose_name='last modified by')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
