from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CustomTokenObtainPairView, NoteViewSet, RegisterView

# Create a router and register the Note viewset
router = DefaultRouter()
router.register(r"notes", NoteViewSet, basename="note")

urlpatterns = [
    path("", include(router.urls)),  # Include all the routes generated by the router
    path("register/", RegisterView.as_view(), name="register"),  # User registration
    path("login/", CustomTokenObtainPairView.as_view(), name="api-login"),  # User login
]
